language: node_js
node_js:
  - "node"
  - "lts/*"

install:
    - yarn

cache:
  directories:
    - "node_modules"

after_success:
  - npm run build
  - cd dist
  - git add --all .
  - git commit -m "Automatically build in travis-ci"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages
